apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-app
  namespace: dev-sardine
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: nginx:1.10
          name: nginx
