apiVersion: v1
kind: Service
metadata:
  labels:
    name: my-app
  name: my-app
  namespace: dev-salmon
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: my-app
  type: NodePort
