apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-app
  namespace: prod-tuna
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: nginx:1.13.8
          name: nginx
          ports:
            - containerPort: 80
